### ISSUE TITLE
Configuring Instapaper service leads to php fatals

### ISSUE THREAD

**Issue by mdrovdahl** [beaulebens/keyring#75]
I haven't had a chance to debug this yet, but at the user/pass entry step of configuring the Instapaper service, a php fatal occurs...in the Fitbit service?

I don't use the Fitbit service, so I simply removed that service file to work around the issue.

```
When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.4.2
Current theme: Susty (version 1.0.0)
Current plugin: Keyring (version 2.0)
PHP version 7.2.31



Error Details
=============
An error of type E_ERROR was caused in line 69 of the file /srv/htdocs/wp-content/plugins/keyring/includes/services/extended/fitbit.php. Error message: Uncaught ArgumentCountError: Too few arguments to function Keyring_Service_Fitbit::fix_access_token_meta(), 1 passed in /wordpress/core/5.4.2/wp-includes/class-wp-hook.php on line 287 and exactly 2 expected in /srv/htdocs/wp-content/plugins/keyring/includes/services/extended/fitbit.php:69
Stack trace:
#0 /wordpress/core/5.4.2/wp-includes/class-wp-hook.php(287): Keyring_Service_Fitbit->fix_access_token_meta(Object(Keyring_Access_Token))
#1 /wordpress/core/5.4.2/wp-includes/plugin.php(206): WP_Hook->apply_filters(Object(Keyring_Access_Token), Array)
#2 /srv/htdocs/wp-content/plugins/keyring/includes/services/extended/instapaper.php(201): apply_filters('keyring_access_...', Object(Keyring_Access_Token))
#3 /wordpress/core/5.4.2/wp-includes/class-wp-hook.php(287): Keyring_Service_Instapaper->verify_token(Array)
#4 /wordpress/core/5.4.2/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /wordpress/core/5.4.2/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 /srv/htdocs/wp-content/plugins/keyring/keyring.php(159): do_action('keyring_instapa...', Array)
#7 /wordpress/core/5.4.2/wp-includes/class-wp-hook.php(287): Keyring::request_handlers('')
#8 /wordpress/core/5.4.2/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#9 /wordpress/core/5.4.2/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#10 /wordpress/core/5.4.2/wp-admin/admin.php(170): do_action('admin_init')
#11 /wordpress/core/5.4.2/wp-admin/tools.php(40): require_once('/wordpress/core...')
#12 {main}
  thrown
```

**Comment by beaulebens** [comment]
This was a PHP7/8 error, but is fixed now. If you download the latest from GH (release coming soon) it should all work.
